# Generated by Django 3.2.8 on 2022-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v_fines',
            name='fine',
        ),
        migrations.AddField(
            model_name='v_fines',
            name='causes',
            field=models.CharField(db_column='causes', max_length=50, null=True, verbose_name='causes'),
        ),
    ]
