# Generated by Django 3.2.8 on 2022-07-12 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vechile_Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(db_column='gender', max_length=50, verbose_name='Gender')),
                ('user_name', models.CharField(db_column='user_name', max_length=50, verbose_name='User_Name')),
                ('user_lastname', models.CharField(db_column='user_lastname', max_length=50, verbose_name='User_Lastname')),
                ('user_email', models.EmailField(blank=True, db_column='user_email', max_length=100, null=True, verbose_name='User_Email')),
                ('user_phone', models.BigIntegerField(db_column='user_phone', verbose_name='User_Phone')),
                ('vechile_year', models.CharField(db_column='vechile_year', max_length=50, verbose_name='Vechile_Year')),
                ('vechile_make', models.CharField(db_column='vechile_make', max_length=50, verbose_name='Vechile_Make')),
                ('vechile_model', models.CharField(db_column='vechile_model', max_length=50, verbose_name='vechile_model')),
                ('vechile_color', models.CharField(db_column='vechile_color', max_length=50, verbose_name='Vechile_Color')),
                ('vechile_mileage', models.CharField(db_column='vechile_mileage', max_length=50, verbose_name='Vechile_Mileage')),
                ('vechile_number', models.CharField(db_column='vechile_number', max_length=50, verbose_name='vechile_number')),
                ('country', models.CharField(db_column='country', max_length=50, null=True, verbose_name='Country')),
                ('state', models.CharField(db_column='state', max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(db_column='city', max_length=50, null=True, verbose_name='City')),
                ('street_name', models.CharField(db_column='street_name', max_length=50, verbose_name='Street_Name')),
                ('house_number', models.CharField(db_column='house_number', max_length=50, verbose_name='House_Number')),
                ('user_image', models.FileField(blank=True, db_column='user_image', upload_to='User/Profile-image/', verbose_name='User_Image')),
                ('vechile_image', models.FileField(blank=True, db_column='Vechile_image', upload_to='User/Vechile-image/', verbose_name='Vechile_image')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Vechile_Register',
            },
        ),
    ]
