# Generated by Django 3.2.8 on 2022-07-13 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_fines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fines',
            name='drunk',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='juvenile_driving',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='over_speed',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='signal_jumping',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='without_helmate',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='without_licence',
        ),
        migrations.AddField(
            model_name='fines',
            name='amount',
            field=models.CharField(db_column='amount', max_length=50, null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='fines',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='fines',
            name='descrption',
            field=models.CharField(db_column='descrption', max_length=50, null=True, verbose_name='Descrption'),
        ),
        migrations.AddField(
            model_name='fines',
            name='prison',
            field=models.CharField(db_column='prison', max_length=50, null=True, verbose_name='prison'),
        ),
        migrations.AddField(
            model_name='fines',
            name='title',
            field=models.CharField(db_column='title', max_length=50, null=True, verbose_name='Title'),
        ),
    ]
