# Generated by Django 3.2.8 on 2022-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20220713_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='fines',
            name='image',
            field=models.FileField(blank=True, db_column='Vechile_image', upload_to='admin/fine-image/', verbose_name='Vechile_image'),
        ),
    ]
