# Generated by Django 3.2.8 on 2022-07-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=50, verbose_name='User_Name')),
                ('vechile_make', models.CharField(db_column='vechile_make', max_length=50, verbose_name='Vechile_Make')),
                ('causes', models.CharField(db_column='causes', max_length=50, null=True, verbose_name='causes')),
                ('amount', models.CharField(db_column='amount', max_length=50, null=True, verbose_name='amount')),
                ('vechile_color', models.CharField(db_column='vechile_color', max_length=50, verbose_name='Vechile_Color')),
                ('vechile_number', models.CharField(db_column='vechile_number', max_length=50, verbose_name='vechile_number')),
                ('order_id', models.CharField(db_column='order_id', max_length=50, null=True, verbose_name='order_id')),
                ('status', models.CharField(db_column='status', max_length=50, null=True, verbose_name='status')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
