# Generated by Django 3.2.8 on 2022-07-19 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='bank_name',
            field=models.CharField(db_column='bank_name', max_length=50, null=True, verbose_name='bank_name'),
        ),
        migrations.AddField(
            model_name='payments',
            name='bank_tex_id',
            field=models.CharField(db_column='bank_tex_id', max_length=50, null=True, verbose_name='bank_tex_id'),
        ),
        migrations.AddField(
            model_name='payments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_mode',
            field=models.CharField(db_column='payment_mode', max_length=50, null=True, verbose_name='payment_mode'),
        ),
        migrations.AddField(
            model_name='payments',
            name='tex_id',
            field=models.BigIntegerField(db_column='tex_id', max_length=100, null=True, verbose_name='tex_id'),
        ),
    ]
