# Generated by Django 3.2.8 on 2022-07-20 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20220719_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tic_id', models.CharField(db_column='tic_id', max_length=50, verbose_name='Tic_id')),
                ('user_name', models.CharField(db_column='user_name', max_length=50, verbose_name='User_Name')),
                ('vechile_num', models.CharField(db_column='vechile_num', max_length=50, verbose_name='Vechile_Num')),
                ('causes', models.CharField(db_column='causes', max_length=50, null=True, verbose_name='causes')),
                ('amount', models.CharField(db_column='amount', max_length=50, null=True, verbose_name='amount')),
                ('complient', models.CharField(db_column='complient', max_length=50, null=True, verbose_name='Complient')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Complient',
            },
        ),
        migrations.AlterField(
            model_name='payments',
            name='tex_id',
            field=models.BigIntegerField(db_column='tex_id', null=True, verbose_name='tex_id'),
        ),
    ]
