# Generated by Django 3.2.8 on 2022-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20220720_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='complient',
            name='user_email',
            field=models.EmailField(blank=True, db_column='user_email', max_length=100, null=True, verbose_name='User_Email'),
        ),
    ]
